version: "3.3"

services:
    nginx-proxy:
        # image: nginx:alpine
        build:
            context: ./dev-proxy
            dockerfile: Dockerfile
        container_name: nginx-proxy
        network_mode: host
        volumes:
            - ./dev-proxy/default.conf:/etc/nginx/conf.d/default.conf
        command: ['nginx-debug' , '-g', 'daemon off;']

    oauth2-proxy:
        image: docker.io/bitnami/oauth2-proxy:7
        network_mode: host
        environment:
            - OAUTH2_PROXY_CLIENT_ID=test-client-istio
            - OAUTH2_PROXY_CLIENT_SECRET=0541a7d6-4fa6-4a12-8738-32a602855a31
            - OAUTH2_PROXY_COOKIE_SECRET=Opya5aptiKF-8KEH6bp5g1MEwsHmtfTINfQmUHJsBjY=
            - OAUTH2_PROXY_UPSTREAMS=static://200
        command: 
            --provider=keycloak
            --email-domain=*
            --skip-provider-button=true
            --login-url=https://login-dev.bit2win.cloud/auth/realms/internal-dev-01/protocol/openid-connect/auth
            --redeem-url=https://login-dev.bit2win.cloud/auth/realms/internal-dev-01/protocol/openid-connect/token
            --validate-url=https://login-dev.bit2win.cloud/auth/realms/internal-dev-01/protocol/openid-connect/userinfo
            --profile-url=https://login-dev.bit2win.cloud/auth/realms/internal-dev-01/protocol/openid-connect/userinfo
            --keycloak-group=/test-group
            --http-address=0.0.0.0:4180
            --scope=test
            --cookie-secure=false
            --pass-basic-auth=false
            --pass-access-token=true
            --set-xauthrequest=true
            --set-authorization-header=true
            --pass-authorization-header=true
            --skip-auth-preflight=true
            --pass-host-header=true
            --skip-jwt-bearer-tokens=true
            --oidc-jwks-url=https://login-dev.bit2win.cloud/auth/realms/internal-dev-01/protocol/openid-connect/certs
            --extra-jwt-issuers=https://login-dev.bit2win.cloud/auth/realms/internal-dev-01=account
            --insecure-oidc-allow-unverified-email=true
            